module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "content",
        "style",
        "refactor",
        "test",
        "chore",
        "ci",
        "perf",
        "revert",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "auth",
        "quiz",
        "dashboard",
        "enrollment",
        "progress",
        "content",
        "ui",
        "deps",
        "api",
        "db",
        "infra",
      ],
    ],
    "subject-empty": [2, "never"],
    "subject-max-length": [2, "always", 72],
    "type-empty": [2, "never"],
    "type-case": [2, "always", "lower-case"],
    "header-max-length": [2, "always", 100],
  },
};
