"""add_timestamps_to_quiz_and_question

Revision ID: 4d69efbfe45b
Revises: 003_add_is_active_to_questions
Create Date: 2026-04-20 15:15:16.323350

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d69efbfe45b"
down_revision: Union[str, Sequence[str], None] = "003_add_is_active_to_questions"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_courses_category"), table_name="courses")
    op.drop_index(op.f("idx_courses_slug"), table_name="courses")
    op.drop_constraint(op.f("uq_courses_slug"), "courses", type_="unique")
    op.create_index(op.f("ix_courses_category"), "courses", ["category"], unique=False)
    op.create_index(op.f("ix_courses_id"), "courses", ["id"], unique=False)
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    op.drop_index(op.f("idx_oauth_provider"), table_name="oauth_accounts")
    op.drop_index(op.f("idx_oauth_user_id"), table_name="oauth_accounts")
    op.add_column(
        "questions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "questions",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("idx_questions_quiz"), table_name="questions")
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.drop_index(op.f("idx_answers_attempt"), table_name="quiz_attempt_answers")
    op.drop_index(op.f("idx_attempts_user_quiz"), table_name="quiz_attempts")
    op.add_column(
        "quizzes",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_quizzes_id"), "quizzes", ["id"], unique=False)
    op.drop_index(op.f("idx_sections_course"), table_name="sections")
    op.drop_constraint(op.f("uq_sections_section_id_str"), "sections", type_="unique")
    op.create_index(op.f("ix_sections_id"), "sections", ["id"], unique=False)
    op.create_index(
        op.f("ix_sections_section_id_str"), "sections", ["section_id_str"], unique=True
    )
    op.drop_index(op.f("idx_progress_user_section"), table_name="user_progress")
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.create_index(
        op.f("idx_progress_user_section"),
        "user_progress",
        ["user_id", "section_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_sections_section_id_str"), table_name="sections")
    op.drop_index(op.f("ix_sections_id"), table_name="sections")
    op.create_unique_constraint(
        op.f("uq_sections_section_id_str"),
        "sections",
        ["section_id_str"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_sections_course"), "sections", ["course_id"], unique=False
    )
    op.drop_index(op.f("ix_quizzes_id"), table_name="quizzes")
    op.drop_column("quizzes", "updated_at")
    op.create_index(
        op.f("idx_attempts_user_quiz"),
        "quiz_attempts",
        ["user_id", "quiz_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_answers_attempt"),
        "quiz_attempt_answers",
        ["attempt_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.create_index(op.f("idx_questions_quiz"), "questions", ["quiz_id"], unique=False)
    op.drop_column("questions", "updated_at")
    op.drop_column("questions", "created_at")
    op.create_index(
        op.f("idx_oauth_user_id"), "oauth_accounts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_oauth_provider"),
        "oauth_accounts",
        ["provider", "provider_user_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.drop_index(op.f("ix_courses_id"), table_name="courses")
    op.drop_index(op.f("ix_courses_category"), table_name="courses")
    op.create_unique_constraint(
        op.f("uq_courses_slug"),
        "courses",
        ["slug"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_courses_slug"), "courses", ["slug"], unique=False)
    op.create_index(op.f("idx_courses_category"), "courses", ["category"], unique=False)
    # ### end Alembic commands ###
